name: Build Resume PDF
on:
  push:
    branches:
      - "master"
jobs:
  release_resume_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Release PDF file
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Resume"
          files: |
            main.pdf

      - name: Commit Artifact to Portfolio
        uses: actions/checkout@v4
        with:
          repository: mostafaayesh/portfolio
          path: 'portfolio'
          token: ${{ secrets.PFSECRET }}

      - name: Copy Resume to Static
        run: cp ./main.pdf portfolio/static/pdf/resume.pdf
      
      - name: Copy Resume to Assets
        run: cp ./main.pdf portfolio/assets/pdf/resume.pdf

      - name: Commit and Push
        run: |
          cd portfolio
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add static/ assets/
          git commit -m "Update Resume"
          git push

          